- title: Reviewer
  contents:
    - name: IEEE TCSVT
      url: https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=76
    - name: Photonics Res.
      url: https://opg.optica.org/prj
    - name: Opt. Express
      url: https://opg.optica.org/oe
    - name: Opt. Letters
      url: https://opg.optica.org/ol
    - name: JOSA A
      url: https://opg.optica.org/josaa/

# - title: Editor
#   contents:
#     - name: Optics Express (EIC)
#       url: https://opg.optica.org/oe
#     - name: Photonics Research (SAE)
#       url: https://opg.optica.org/prj